### ISSUE TITLE
serverGame.h is missing

### ISSUE THREAD

**Issue by vitacell** [igp7/connect-3x3#1]
bash-4.3$ make
gcc -c -g -Wall game.c
gcc -c -g -Wall clientGame.c
gcc game.o clientGame.o -o clientGame
gcc -c -g -Wall serverGame.c
serverGame.c:1:24: error fatal: serverGame.h: No existe el fichero o el directorio
compilación terminada.

**Comment by igp7** [comment]
Already added, thanks for the warning.
